### ISSUE TITLE
Error when trying to reproduce on Colab Pro Plus with A100 GPU

### ISSUE THREAD

**Issue by mrm8488** [LambdaLabsML/examples#14]
I am getting the following error when runing the notebook on colab pro plus with one A100 GPU:

```
  File "main.py", line 812, in <module>
    trainer = Trainer.from_argparse_args(trainer_opt, **trainer_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/properties.py", line 421, in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py", line 52, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 446, in __init__
    terminate_on_nan,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/training_trick_connector.py", line 50, in on_trainer_init
    self.configure_accumulated_gradients(accumulate_grad_batches)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/training_trick_connector.py", line 66, in configure_accumulated_gradients
    raise TypeError("Gradient accumulation supports only int and dict types")
TypeError: Gradient accumulation supports only int and dict types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 909, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined
```

**Comment by madaan** [comment]
This can happen if the model (`sd-v1-4-full-ema.ckpt`) is not present where the `main.py` expects it to be (local directory). Is the model present in your local direcotry?

**Comment by viba98** [comment]
I face the same issue. 
But in the Pokemon example notebook, the ckpt_ path is defined already here: 
ckpt_path = hf_hub_download(repo_id="CompVis/stable-diffusion-v-1-4-original", filename="sd-v1-4-full-ema.ckpt", use_auth_token=True)
Am I missing something?

**Comment by viba98** [comment]
I did that too, but I still receive this error: 
<img width="1002" alt="Screenshot 2022-10-06 at 15 56 09" src="https://user-images.githubusercontent.com/32447352/194290190-771026d9-1695-4f6b-96e3-b582a03388a6.png">

**Comment by devonbrackbill** [comment]
Has anyone been able to resolve this? 

1. I don't think it's a path issue b/c `ckpt_path = hf_hub_download(repo_id="CompVis/stable-diffusion-v-1-4-original", filename="sd-v1-4-full-ema.ckpt", use_auth_token=True)` returns the right path in the `/root` directory to the `.ckpt` file.
2. And I don't think it's the wrong argument to `lightning.trainer.accumulate_grad_batches="$ACCUMULATE_BATCHES"` because I have `ACCUMULATE_BATCHES = 1` set to one.

For reference, I'm trying to train this on a single GPU, and so is the OP from the sounds of it (running "the notebook on colab pro plus with one A100 GPU") , so I don't know if that affects the setup here (in particular does ACCUMULATE_BATCHES need to be a different value?)

For reference, my `python main.py` call is (had to change `--gpus "$gpu_list" \` to `--auto_select_gpus \` b/c I was getting a different error (`error: argument --gpus: invalid _gpus_allowed_type value: ''`):

```
(python main.py \
    -t \
    --base "$YAML-PATH" \
    --auto_select_gpus \
    --scale_lr False \
    --num_nodes 1 \
    --check_val_every_n_epoch 10 \
    --finetune_from "$ckpt_path" \
    data.params.batch_size="$BATCH_SIZE" \
    lightning.trainer.accumulate_grad_batches="$ACCUMULATE_BATCHES" \
    data.params.validation.params.n_gpus="$NUM_GPUS" \
)
```

with 
```
BATCH_SIZE = 4
N_GPUS = 1
ACCUMULATE_BATCHES = 1
```

**Comment by treksis** [comment]
same issue here with colab a100

```
main.py: error: argument --gpus: invalid _gpus_allowed_type value: ''
```

**Comment by lvsi-qi** [comment]
> 解决了对NUM_GPUS的更改。在带有 A100 的 colab pro+ 上运行
> 
> ```
> # A100:
> BATCH_SIZE = 4
> NUM_GPUS = 1
> ACCUMULATE_BATCHES = 1
> 
> gpu_list = ",".join((str(x) for x in range(NUM_GPUS))) + ","
> print(f"Using GPUs: {gpu_list}")
> ```
> 
> <img alt="图像" width="320" src="https://user-images.githubusercontent.com/54779707/200673173-91e6284b-5b35-4642-a7d8-616a71f6c30f.png">

Hello,I encountered this problem on colab. Have you encountered it?How to solve this problem?
![53c5de0017b1d1461791d499f5b4726](https://user-images.githubusercontent.com/105265820/233955188-93562abe-b8cd-46c2-95dc-401396fbda92.png)

**Comment by treksis** [comment]
It has been a while. I would rather use this colab notebook for training.
https://github.com/Linaqruf/kohya-trainer
