### ISSUE TITLE
NameError: name 'trainer' is not defined

### ISSUE THREAD

**Issue by lvsi-qi** [LambdaLabsML/examples#61]
(sd) (stable-diffusion-main) E:\GitHub\stable-diffusion-main>python main.py
Global seed set to 23
Traceback (most recent call last):
  File "E:\GitHub\stable-diffusion-main\main.py", line 673, in <module>
    model = instantiate_from_config(config.model)
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\base.py", line 190, in _format_and_raise
    format_and_raise(
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "E:\GitHub\stable-diffusion-main\.venv\lib\site-packages\omegaconf\dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GitHub\stable-diffusion-main\main.py", line 940, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

What should I do?

**Comment by minyoung-jun** [comment]
Me too

**Comment by megatran** [comment]
Here's my fix for this https://github.com/LambdaLabsML/examples/pull/65

**Comment by sshh12** [comment]
Fixed this by using the full config yaml here: https://raw.githubusercontent.com/justinpinkney/stable-diffusion/main/configs/stable-diffusion/pokemon.yaml (rather than copy pasting from readme which was incomplete)
